### ISSUE TITLE
The rotation angle of SmallKnob does not match the angle of finger sliding. 

### ISSUE THREAD

**Issue by rushairer** [AudioKit/Controls#8]
### macOS Version(s) Used to Build

macOS 13 Ventura

### Xcode Version(s)

Xcode 14

### Description

The rotation angle of SmallKnob does not match the angle of finger sliding.

Can you fix it?

**Comment by aure** [comment]
Small Knob is controlled with vertical/horizontal movement, not angle.

**Comment by rushairer** [comment]
> 

Maybe I don't understand the habit of music industry software, and this interaction way is beyond my understanding.

😂

**Comment by aure** [comment]
Another knob in there should work for you. Control is really kind of meant to allow you to build your own with a few examples to look at.

**Comment by rushairer** [comment]
I had a Wheelpicker package  https://github.com/rushairer/ABWheelPickerModifier

Using in my application: https://github.com/rushairer/ABWheelPickerModifier

**Comment by aure** [comment]
Very cool work! I'd welcome your input on Controls if you want to get involved, making pull requests, etc. We have a discussion section the AudioKit Discord for Controls if you want an invite.
