### ISSUE TITLE
Add audio to the demo project

### ISSUE THREAD

**Issue by shadyk** [AudioKit/Controls#9]
### Description

it will great if u can embed the audio engine tin the demo project with the keyboard view. 

### Proposed Solution

it will great if u can embed the audio engine tin the demo project with the keyboard view. 

### Describe Alternatives You've Considered

it will great if u can embed the audio engine tin the demo project with the keyboard view.

**Comment by NickCulbertson** [comment]
Hey Shadyk! Check out the AudioKit Cookbook (https://github.com/AudioKit/Cookbook) for examples of using Keyboard with AudioEngine. The piano layouts in the recipes use the Keyboard package.
